// Code generated by protoc-gen-svc. DO NOT EDIT.
// source: pkg/pb/rpc.proto
package pb

import "google.golang.org/grpc"

func RegisterBevisChangGrpcService(s *grpc.Server, srv BevisChangServer) {
	RegisterBevisChangServer(s, srv)
}
