// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AmazingTalker/bevis-chang/pkg/dao (interfaces: RecordDAO,MemberDAO)

// Package daomock is a generated GoMock package.
package daomock

import (
	context "context"
	reflect "reflect"
	time "time"

	dao "github.com/AmazingTalker/bevis-chang/pkg/dao"
	daokit "github.com/AmazingTalker/go-rpc-kit/daokit"
	gomock "github.com/golang/mock/gomock"
)

// MockRecordDAO is a mock of RecordDAO interface.
type MockRecordDAO struct {
	ctrl     *gomock.Controller
	recorder *MockRecordDAOMockRecorder
}

// MockRecordDAOMockRecorder is the mock recorder for MockRecordDAO.
type MockRecordDAOMockRecorder struct {
	mock *MockRecordDAO
}

// NewMockRecordDAO creates a new mock instance.
func NewMockRecordDAO(ctrl *gomock.Controller) *MockRecordDAO {
	mock := &MockRecordDAO{ctrl: ctrl}
	mock.recorder = &MockRecordDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordDAO) EXPECT() *MockRecordDAOMockRecorder {
	return m.recorder
}

// CreateRecord mocks base method.
func (m *MockRecordDAO) CreateRecord(arg0 context.Context, arg1 *dao.Record, arg2 ...daokit.Enrich) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateRecord", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRecord indicates an expected call of CreateRecord.
func (mr *MockRecordDAOMockRecorder) CreateRecord(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecord", reflect.TypeOf((*MockRecordDAO)(nil).CreateRecord), varargs...)
}

// GetRecord mocks base method.
func (m *MockRecordDAO) GetRecord(arg0 context.Context, arg1 string) (*dao.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", arg0, arg1)
	ret0, _ := ret[0].(*dao.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockRecordDAOMockRecorder) GetRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockRecordDAO)(nil).GetRecord), arg0, arg1)
}

// ListRecords mocks base method.
func (m *MockRecordDAO) ListRecords(arg0 context.Context, arg1 dao.ListRecordsOpt) ([]dao.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecords", arg0, arg1)
	ret0, _ := ret[0].([]dao.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecords indicates an expected call of ListRecords.
func (mr *MockRecordDAOMockRecorder) ListRecords(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecords", reflect.TypeOf((*MockRecordDAO)(nil).ListRecords), arg0, arg1)
}

// MockMemberDAO is a mock of MemberDAO interface.
type MockMemberDAO struct {
	ctrl     *gomock.Controller
	recorder *MockMemberDAOMockRecorder
}

// MockMemberDAOMockRecorder is the mock recorder for MockMemberDAO.
type MockMemberDAOMockRecorder struct {
	mock *MockMemberDAO
}

// NewMockMemberDAO creates a new mock instance.
func NewMockMemberDAO(ctrl *gomock.Controller) *MockMemberDAO {
	mock := &MockMemberDAO{ctrl: ctrl}
	mock.recorder = &MockMemberDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberDAO) EXPECT() *MockMemberDAOMockRecorder {
	return m.recorder
}

// CreateMember mocks base method.
func (m *MockMemberDAO) CreateMember(arg0 context.Context, arg1 *dao.Member, arg2 ...daokit.Enrich) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockMemberDAOMockRecorder) CreateMember(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockMemberDAO)(nil).CreateMember), varargs...)
}

// DeleteMember mocks base method.
func (m *MockMemberDAO) DeleteMember(arg0 context.Context, arg1 int64, arg2 ...daokit.Enrich) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMember", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockMemberDAOMockRecorder) DeleteMember(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockMemberDAO)(nil).DeleteMember), varargs...)
}

// ListMembers mocks base method.
func (m *MockMemberDAO) ListMembers(arg0 context.Context, arg1 *time.Time, arg2 ...daokit.Enrich) ([]dao.Member, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListMembers", varargs...)
	ret0, _ := ret[0].([]dao.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMemberDAOMockRecorder) ListMembers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMemberDAO)(nil).ListMembers), varargs...)
}

// UpdateMember mocks base method.
func (m *MockMemberDAO) UpdateMember(arg0 context.Context, arg1 *dao.Member, arg2 ...daokit.Enrich) (*dao.Member, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMember", varargs...)
	ret0, _ := ret[0].(*dao.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockMemberDAOMockRecorder) UpdateMember(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockMemberDAO)(nil).UpdateMember), varargs...)
}
